# Pivot Tables, Cross Tab #

In [1]:
import numpy as np
import pandas as pd

##### *1. Pivot Table* #####

In [7]:
data = {
'Date': pd.date_range('2023-01-01', periods=20),
'Product': ['A', 'B', 'C', 'D'] * 5,
'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
'Sales': np.random.randint(100, 1000, 20),
'Units': np.random.randint(10, 100, 20),
'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}
df = pd.DataFrame(data)

df ['Month'] = df['Date'].dt.month_name()
df ['Quarter'] = 'Q' + df ['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    907     88   John  January      Q1
1  2023-01-02       B   West    678     18   Mary  January      Q1
2  2023-01-03       C  North    540     98    Bob  January      Q1
3  2023-01-04       D  South    130     26  Alice  January      Q1
4  2023-01-05       A   East    885     65   John  January      Q1
5  2023-01-06       B   West    314     38   Mary  January      Q1
6  2023-01-07       C  North    253     66    Bob  January      Q1
7  2023-01-08       D  South    388     22  Alice  January      Q1
8  2023-01-09       A   East    564     33   John  January      Q1
9  2023-01-10       B   West    116     86   Mary  January      Q1
10 2023-01-11       C  North    867     17    Bob  January      Q1
11 2023-01-12       D  South    591     66  Alice  January      Q1
12 2023-01-13       A   East    543     82   John  January      Q1
13 2023-01-14       B   West    828     92   Mary  January      Q1
14 2023-01-15       C  North    702     29    Bob  January      Q1
15 2023-01-16       D  South    791     49  Alice  January      Q1
16 2023-01-17       A   East    255     12   John  January      Q1
17 2023-01-18       B   West    872     63   Mary  January      Q1
18 2023-01-19       C  North    982     89    Bob  January      Q1
19 2023-01-20       D  South    137     36  Alice  January      Q1

In [ ]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product')  # it gives the mean values

Product      A      B      C      D
Region
East     542.8    NaN    NaN    NaN
North      NaN    NaN  561.6    NaN
South      NaN    NaN    NaN  547.2
West       NaN  700.6    NaN    NaN

In [6]:
pivot2 = pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')
pivot2

         Sales                      Units
Product      A      B      C      D     A     B     C     D
Region
East     542.8    NaN    NaN    NaN  59.4   NaN   NaN   NaN
North      NaN    NaN  561.6    NaN   NaN   NaN  63.2   NaN
South      NaN    NaN    NaN  547.2   NaN   NaN   NaN  70.2
West       NaN  700.6    NaN    NaN   NaN  56.8   NaN   NaN

##### *2. Cross Tab* #####

In [ ]:
pd.crosstab(df['Region'],df['Product']) # it gives count values

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0